### ISSUE TITLE
some books failed to include chapters

### ISSUE THREAD

**Issue by deborahgu** [deborahgu/abbyy-to-epub3#38]
per @mekarpeles: " every once in a while our epub will fail to include a chapter causing the resulting ebook to `fatal` fail epubcheck".

**Comment by mekarpeles** [comment]
This may have been a regression specific to github.com/internetarchive/abbyy-to-epub3 fork

**Comment by deborahgu** [comment]
Yes, this definitely seems to be a problem in that fork and not this code branch.  I've been tracing the differences between the two repos, hoping to bring them into sync without losing whatever fix prevented this behavior.
