### ISSUE TITLE
make epubcheck validation more useful

### ISSUE THREAD

**Issue by deborahgu** [deborahgu/abbyy-to-epub3#40]
Per @mekarpeles:

> *Validation* -- is there a heuristic we can use to reliably identify catastrophic errors (e.g. a subset of `--epubcheck` errors)? We don't necessarily want to raise errors in ebook generation if/when we hit something like a "duplicate author" issue, assuming the epub opens as expected. We would like an option to error out if we start generating epubs that readers can't open (e.g. missing many pages, abnormally small filesizes?). We're looking for ways to detect when something in our system inevitably changes and our pipeline breaks and starts producing bad epubs.
> EDIT: It looks like we may be able to use `fatal` instead of `error` for `epubcheck` (edited)

**Comment by mekarpeles** [comment]
the addition of an epubcheck `mode` (e.g. `fatal`) is introduced here: https://github.com/internetarchive/epub3/pull/11

**Comment by deborahgu** [comment]
Thanks. there's enough unrelated changes in that merge that I will just point-by-point add similar lines of code to a branch over here, especially since some of those changes will be explicitly contradicted with the image fixes.
